blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Contributing Guide
    url: https://github.com/STRONG-OE-200/CAREON-BACKEND/blob/dev/.github/CONTRIBUTING.md
    about: ê¸°ì—¬ ê·œì¹™ê³¼ ì»¤ë°‹/ë¸Œëœì¹˜ ì»¨ë²¤ì…˜ì„ ë°˜ë“œì‹œ í™•ì¸í•´ì£¼ì„¸ìš”.
